version: "3"
services:
  gql:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
        #BUILD: 'local'
    image: gql20:1
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      APP_DEBUG: 'true'
      APP_KEY: base64:joUD24iQhw/uWEWR002FPF/QJrmL2NuNj3JKS0v9Hvc=
      DATABASE_URL: mysql://devuser:devpass@144.44.1.2/gql20
    networks:
      gql_net:
        ipv4_address: 144.44.1.1

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gql20
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 9906:3306
    networks:
      gql_net:
        ipv4_address: 144.44.1.2
volumes:
  db_data: {}
networks:
  gql_net:
    ipam:
      driver: default
      config:
        - subnet: 144.44.0.0/16
